### ISSUE TITLE
Remove the need to add .lazy-bg class to CSS manually

### ISSUE THREAD

**Issue by marcamos** [fromtheoutfit/lazyload#1]
It would be much more convenient if this script was updated to let the user skip the step of adding…
```css
.lazy-bg {
  background-image: none !important;
}
```
…to their CSS manually. Look into it.
